# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=200)),
                ('segment', models.CharField(max_length=50, null=True)),
                ('sector', models.CharField(max_length=50, null=True)),
                ('voivodship', models.CharField(max_length=30, null=True)),
                ('value', models.FloatField()),
                ('total_actions', models.BigIntegerField()),
                ('debut_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('nominal_price', models.FloatField()),
                ('market_money', models.FloatField()),
                ('volume', models.FloatField()),
                ('open_positions', models.IntegerField()),
                ('open_positions_value', models.FloatField()),
                ('changes', models.FloatField()),
                ('transactions_num', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='gpw.Company', unique_for_date='date')),
            ],
        ),
    ]
