# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='changes',
            new_name='change',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='company',
        ),
        migrations.AddField(
            model_name='statistics',
            name='isin',
            field=models.CharField(max_length=15, unique_for_date='date')
        ),
    ]
