version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=gpw
      - POSTGRES_PASSWORD=gpw
      - POSTGRES_DB=gpw
  web:
    build: images/web
    ports:
      - "8000:8000"
    command: ./run_django_server.sh
    volumes:
      - /home/mateusz/Projects/gpw:/gpw
    links:
      - postgres
  notebook:
    build: images/notebook
    ports:
      - "8888:8888"
    command: ./run_notebook.sh
    volumes:
      - /home/mateusz/Projects/gpw:/gpw
    links:
      - postgres