version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=gpw
      - POSTGRES_PASSWORD=gpw
      - POSTGRES_DB=gpw
  web:
    build: .
    ports:
      - "8000:8000"
    command: ./entrypoint.sh
    volumes:
      - /home/mateusz/Projects/gpw:/gpw
    links:
      - postgres